bundler_args: --without development
sudo: false
language: ruby
addons:
  apt:
    packages:
      # required for unf_ext gem
      - build-essential
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
script:
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  - RAKE_ENV=ci bundle exec rake lint
#  - BEAKER_set=ubuntu-1404-docker RAKE_ENV=ci bundle exec rake acceptance
rvm:
# see http://rubies.travis-ci.org/
  - 1.9.3
  - 2.0.0
  - 2.1.10
env:
#  - BEAKER_set="debian-8-docker"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  # doesn't work with allowdupe param
  #- PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.7.0" STRICT_VARIABLES=yes
matrix:
  include:
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_install=yes RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=ubuntu-14.04
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_install=yes RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=centos-7
      script: bundle exec rake beaker
      services: docker
      sudo: required
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_install=yes RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=debian-8
      script: bundle exec rake beaker
      services: docker
      sudo: required
  allow_failures:
    - env: PUPPET_install=yes RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=ubuntu-14.04
    - env: PUPPET_install=yes RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=centos-7
    - env: PUPPET_install=yes RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=debian-8