bundler_args: --without development
sudo: false
language: ruby
addons:
  apt:
    packages:
      # required for unf_ext gem
      - build-essential
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
script:
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  - RAKE_ENV=ci bundle exec rake lint
#  - BEAKER_set=ubuntu-1404-docker RAKE_ENV=ci bundle exec rake acceptance
rvm:
# see http://rubies.travis-ci.org/
  - 2.3.3
  - 2.4.4
  - 2.5.5
env:
  - PUPPET_VERSION="~> 4.10" STRICT_VARIABLES=yes PARALLEL_TEST_PROCESSORS=4
  - PUPPET_VERSION="~> 5.5" STRICT_VARIABLES=yes PARALLEL_TEST_PROCESSORS=4
  - PUPPET_VERSION="~> 6.0" STRICT_VARIABLES=yes PARALLEL_TEST_PROCESSORS=4
matrix:
  include:
    #- rvm: 2.3.3
    #  dist: trusty
    #  env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=centos7-3.8
    #  script: bundle exec rake acceptance
    #  services: docker
    #  sudo: required
    - rvm: 2.3.3
      dist: xenial
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian9-4.10
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.3
      dist: xenial
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian8-4.10
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.3
      dist: xenial
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian9-5.5
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.3
      dist: xenial
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian9-6.3
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.3
      dist: xenial
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=sles13-3.8
      script: bundle exec rake acceptance
      services: docker
      sudo: required
  allow_failures:
    - env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=sles13-3.8
    - env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian8-4.10
    - env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian9-4.10
    - env: PUPPET_VERSION="~> 4.10" STRICT_VARIABLES=yes PARALLEL_TEST_PROCESSORS=4
