bundler_args: --without development
sudo: false
language: ruby
addons:
  apt:
    packages:
      # required for unf_ext gem
      - build-essential
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
script:
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
  - RAKE_ENV=ci bundle exec rake lint
#  - BEAKER_set=ubuntu-1404-docker RAKE_ENV=ci bundle exec rake acceptance
rvm:
# see http://rubies.travis-ci.org/
  - 2.3.3
  - 2.4.4
  - 2.5.1
env:
#  - BEAKER_set="debian-8-docker"
  - PUPPET_VERSION="~> 4.9.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 4.10.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 5.5.0" STRICT_VARIABLES=yes
matrix:
  include:
    - rvm: 2.3.2
      dist: trusty
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=centos7-3.8
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    #- rvm: 2.3.2
    #  dist: trusty
    #  env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian8-3.4
    #  script: bundle exec rake acceptance
    #  services: docker
    #  sudo: required
    - rvm: 2.3.2
      dist: trusty
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian8-3.8
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.2
      dist: trusty
      env: RAKE_ENV=ci BEAKER_debug=true BEAKER_set=debian8-4.8
      script: bundle exec rake acceptance
      services: docker
      sudo: required
    - rvm: 2.3.2
      dist: trusty
      # includes puppet provisioning (will included latest puppet version)
      env: PUPPET_install=yes RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=ubuntu-14.04
      script: bundle exec rake acceptance
      services: docker
      sudo: required
  exclude:
    - rvm: 2.3.3
      env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
    - rvm: 2.3.3
      env: PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
#  allow_failures:
#    - env: RAKE_ENV=ci PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=debian8-3.8
