bundler_args: --without development
sudo: false
services:
  - docker
addons:
  apt:
    packages:
      # required for unf_ext gem
      - build-essential
cache:
  - bundler
  - directories:
    - $HOME/librarian-puppet
script:
  - RAKE_ENV=ci bundle exec rake validate
  - RAKE_ENV=ci bundle exec rake spec
#  - RAKE_ENV=ci bundle exec rake lint
  - RAKE_ENV=ci bundle exec rake acceptance
rvm:
# google-api-client doesn't support ruby < 2.0
#  - 1.9.3
  - 2.0.0
  - 2.1.10
env:
  - BEAKER_set="ubuntu-1404-docker"
  - PUPPET_VERSION="~> 3.4.0"
  - PUPPET_VERSION="~> 3.5.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - PUPPET_VERSION="~> 3.7.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 3.8.0" STRICT_VARIABLES=yes FUTURE_PARSER=yes
  - PUPPET_VERSION="~> 4.0" STRICT_VARIABLES=yes